### ISSUE TITLE
Sign in issues

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#538]
I am constantly needing to sign in to ZenHub... it is always closing the popup windows, but only from my own repositories. If I look at the ZenHubIO boards and click on an issue, the popup stays open without any problems.

![zenhub-sign-in](https://cloud.githubusercontent.com/assets/136959/12148521/8ad2904e-b464-11e5-9242-0e06edc765d7.gif)

**Comment by Mottie** [comment]
I have revoked ZenHub's access and removed the extension several times, and I am still getting this behavior. Is there another cache somewhere I can clear to see if it helps?

**Comment by Mottie** [comment]
This problem is really making ZenHub unusable for me :crying_cat_face:

**Comment by azenMatt** [comment]
Sorry to hear you are having these problems @Mottie - we are looking into this now and will keep you updated

**Comment by azenMatt** [comment]
Hi @Mottie - is:

![image](https://cloud.githubusercontent.com/assets/7584089/12206759/835c8308-b5f7-11e5-9958-b97bca56a16d.png)

A separate extension? Can you let me know which one so I can test to see if it is impacting?

**Comment by Mottie** [comment]
That is [Octotree](https://github.com/buunguyen/octotree). I did disable all extensions except ZenHub and the issue was still occurring.

**Comment by Mottie** [comment]
Here is another gif for your enjoyment... only ZenHub extension is enabled

![zenhub](https://cloud.githubusercontent.com/assets/136959/12207268/38b198b6-b60b-11e5-906e-021781383c80.gif)

**Comment by Mottie** [comment]
I'm also seeing these errors:

![2016-01-08 13_48_18-developer tools - https___github com_zenhubio_support_issues_538](https://cloud.githubusercontent.com/assets/136959/12207841/934ac196-b60e-11e5-9a90-0d83c78a799f.png)

**Comment by azenMatt** [comment]
Hi @Mottie - wanted to give you an update that we are still looking into this as a priority - we hope to have this fixed for you very soon. 

cc @pnavarrc

**Comment by Mottie** [comment]
Thanks for the update!

**Comment by viddo** [comment]
Another one getting these 401 errors consistently. Doesn't happen all the time, but is definitely more prevalent when I've got more than one board selected on the "boards" view/popup.

**Comment by azenMatt** [comment]
Hi @viddo @Mottie - I am also getting these errors! 

We are close to having a fix live for this - thanks for you patience while we get this shipped!

**Comment by viddo** [comment]
:+1: :kiss:

**Comment by azenMatt** [comment]
We just released 2.15.11 that contains a fix for this, 

We have been seeing an increase in 401 'invalid credentials' errors from the GitHub API, which previously were handled by logging you out... 

We now handle this cases better so you should stay logged in and have your action completed. 

We are awaiting feedback from the GitHub API team to see if there is a particular change on their side that would cause this invalidation case to start happening more frequently. 


As users that were getting this consistently rather than randomly - would you be able to confirm if this is now working ok for you?

**Comment by Mottie** [comment]
Yes! Everything appears to be good now.

Thanks so much!

**Comment by azenMatt** [comment]
great to hear!

**Comment by qa-padmanaban** [comment]
Zenhub not opening in my chrome and  Firefox browser

--In chrome(UpTodate)
  I have cleared all cookies and disabled all extensions except "Zenhub" still facing  an below issue.
![zenhub error](https://user-images.githubusercontent.com/25523221/28764356-7b9f99dc-75e2-11e7-9bb3-f6934d0d041f.png)

**Comment by kendramoroz** [comment]
@qa-padmanaban following up via email! Be in touch shortly.
